# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:16.19.0
commands:
  restore_cache_and_install_pkgs:
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm i

jobs:
  build_repo:
    executor: node_executor
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    executor: node_executor
    steps:
      - restore_cache_and_install_pkgs
      - run: npm run test
  analyze:
    executor: node_executor
    steps:
      - restore_cache_and_install_pkgs
      - run: npm audit

workflows:
  proj_pipeline:
    jobs:
      - build_repo
      - test:
          requires:
            - build_repo
      - analyze:
          requires:
            - test
